### ISSUE TITLE
Chapter 5, page 121

### ISSUE THREAD

**Issue by SweetyPagaria** [PacktPublishing/DP-203-Azure-Data-Engineer-Associate-Certification-Guide#1]
I am trying to execute the below SQL, but encounter issue. Please help. Thanks.

![179899994-bf0b3356-9c2b-4c96-846c-d28a10441d97](https://user-images.githubusercontent.com/106649006/180942436-e31d3560-adf8-4d3e-a848-06cd18d422d2.png)

.

**Comment by SweetyPagaria** [comment]
[tanthiamhuat](https://github.com/tanthiamhuat) This is the correct repo link for your query related to the title.

**Comment by tanthiamhuat** [comment]
Thanks, but I actually solve the issue already. We need to have that Dedicated Pools setup and connect to it. Using Built-in will not work.
