### ISSUE TITLE
Error running Spark Notebooks in Synapse

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/DP-203-Azure-Data-Engineer-Associate-Certification-Guide#2]
Hi,

I purchased the DP-203 book and have provisioned resources as outlined in the chapters. However, when it comes to the Spark code samples, I am getting errors in Synapse when trying to run the second block of code (see below) using a new Notebook. 

**Note: I am not using Azure Databricks, so I'm not running the storage setup block.**

When I try to run this cell:

```Pyspark
from pyspark.sql.functions import *

columnNames = ["tripId","driverId","customerId","cabId","tripDate","startLocation","endLocation"]
tripData = [
  ('100', '200', '300', '400', '20220101', 'New York', 'New Jersey'),
  ('101', '201', '301', '401', '20220102', 'Tempe', 'Phoenix'),
  ('102', '202', '302', '402', '20220103', 'San Jose', 'San Franciso'),
  ('103', '203', '303', '403', '20220102', 'New York', 'Boston'),
  ('104', '204', '304', '404', '20220103', 'New York', 'Washington'),
  ('105', '205', '305', '405', '20220201', 'Miami', 'Fort Lauderdale'),
  ('106', '206', '306', '406', '20220202', 'Seattle', 'Redmond'),
  ('107', '207', '307', '407', '20220203', 'Los Angeles', 'San Diego'),
  ('108', '208', '308', '408', '20220301', 'Phoenix', 'Las Vegas'),
  ('109', '209', '309', '409', '20220302', 'Washington', 'Baltimore'),
  ('110', '210', '310', '410', '20220303', 'Dallas', 'Austin'),
  ('111', '211', '311', '411', '20220303', 'New York', 'New Jersey'),
  ('112', '212', '312', '412', '20220304', 'New York', 'Boston'),
  ('113', '212', '312', '412', '20220401', 'San Jose', 'San Ramon'),
  ('114', '212', '312', '412', '20220404', 'San Jose', 'Oakland'),
  ('115', '212', '312', '412', '20220404', 'Tempe', 'Scottsdale'),
  ('116', '212', '312', '412', '20220405', 'Washington', 'Atlanta'),
  ('117', '212', '312', '412', '20220405', 'Seattle', 'Portland'),
  ('118', '212', '312', '412', '20220405', 'Miami', 'Tampa')
]
df = spark.createDataFrame(data= tripData, schema = columnNames)

# Split the data according the current timestamp and write to store as parquet files
dftripDate = df.withColumn("tripDate", to_timestamp(col("tripDate"), 'yyyyMMdd')) \
           .withColumn("year", tripDate_format(col("tripDate"), "yyyy")) \
           .withColumn("month", tripDate_format(col("tripDate"), "MM")) \
           .withColumn("day", tripDate_format(col("tripDate"), "dd"))

dftripDate.show(truncate=False)

dftripDate.write.partitionBy("year", "month", "day").mode("overwrite").parquet(commonPath + "/partition/")
```

I get this error message `InvalidHttpRequestToLivy: Your Spark job requested 24 vcores. However, the workspace has a 12 core limit. Try reducing the numbers of vcores requested or increasing your vcore quota. HTTP status code: 400. Trace ID: 92fd0722-d642-4b71-8e60-79d2c4a5e3a0.`

However when I increase the scaling (vcore limit), the error still persists albeit with a slightly different message. `InvalidHttpRequestToLivy: Your Spark job requested 192 vcores. However, the workspace has a 12 core limit. Try reducing the numbers of vcores requested or increasing your vcore quota. HTTP status code: 400. Trace ID: d45d2403-7e9a-4f26-bd06-d620013a1993.`

This seems insane with regard to the size of this sample data I'm trying to create. I'm new to Spark but this seemed straightforward. Is there something I'm missing?

Thanks for your help!

**Comment by newtonalex** [comment]
Hi,

Yes, the above code should work even with 4-5 cores. Did your spark session run any other code segment before this sample ? Can you try running it on a fresh session?

**Comment by ghost** [comment]
I was able to get this to work after submitting a vCore quota increase through Azure. Also in this section below, tripDate_format throws an error and should be changed to date_format:

dftripDate = df.withColumn("tripDate", to_timestamp(col("tripDate"), 'yyyyMMdd')) \\
           .withColumn("year", **tripDate_format**(col("tripDate"), "yyyy")) \
           .withColumn("month", **tripDate_format**(col("tripDate"), "MM")) \
           .withColumn("day", **tripDate_format**(col("tripDate"), "dd"))

**Comment by blalonde-tryeverything** [comment]
This has been resolved.
